### ISSUE TITLE
Could not find com.kakao.ad:tracker:0.3.7

### ISSUE THREAD

**Issue by leesohyun13** [soundgym/react-native-kakao-ad#2]
react-native android에서 빌드 에러가 발생합니다. 따로 설정해줘야 하는 부분이 있을까요?

`Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.kakao.ad:tracker:0.3.7.
`

**Comment by Bang9** [comment]
@leesohyun13 아래와 같은 설정을 `project/android/build.gradle` 파일에 추가해보시겠어요?
```diff
allprojects {
    repositories {
+       google()
+       jcenter()
    }
}

subprojects {
    repositories {
        mavenCentral()
+       maven {
+           url 'http://devrepo.kakao.com:8088/nexus/content/groups/public/'
+       }
    }
}
```

**Comment by leesohyun13** [comment]
해결되었습니다. 감사합니다 ㅎㅎ
